# -*- coding: utf-8 -*-
"""Week2Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nxubVcG8x0_W_79UeXSzDEbTf6ZUmQu2
"""

# Netflix User Analytics Assignment
# Import Libraries

import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# For Google Colab users
from google.colab import files

print("Upload Dataset 2.csv")
uploaded = files.upload()

file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name)

print("\nFirst 5 Records:")
print(df.head())

# Q2. Number of Rows and Columns

print("\nQ2. Dataset Shape")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

# Q3. Column Names

print("\nQ3. Column Names")
print(df.columns.tolist())

# Q4. Numerical and Categorical Features

numerical_features = df.select_dtypes(include=np.number).columns.tolist()
categorical_features = df.select_dtypes(exclude=np.number).columns.tolist()

print("\nQ4. Numerical Features")
print(numerical_features)

print("\nCategorical Features")
print(categorical_features)

# Q5. Missing Values

print("\nQ5. Missing Values")
print(df.isnull().sum())

# Q6. Average Age

avg_age = df["Age"].mean()

print("\nQ6. Average Age")
print(avg_age)

# Q7. Average Watch Hours

avg_watch = df["WatchHoursPerWeek"].mean()

print("\nQ7. Average Watch Hours Per Week")
print(avg_watch)

# Q8. Average Monthly Spending

avg_spend = df["MonthlySpend"].mean()

print("\nQ8. Average Monthly Spending")
print(avg_spend)

# Q9. Subscription Category Count

print("\nQ9. Subscription Counts")
print(df["SubscriptionType"].value_counts())

# Q10. Renewal Percentage

renewal_percentage = (
    (df["SubscriptionRenewed"] == "Yes").sum()
    / len(df)
) * 100

print("\nQ10. Renewal Percentage")
print(f"{renewal_percentage:.2f}%")

# Q11. Convert Categorical Features

df_encoded = df.copy()

label_encoders = {}

for column in df_encoded.select_dtypes(include="object").columns:
    le = LabelEncoder()
    df_encoded[column] = le.fit_transform(df_encoded[column])
    label_encoders[column] = le

print("\nQ11. Encoded Dataset")
print(df_encoded.head())

# Q12. Define X and y

X = df_encoded.drop("SubscriptionRenewed", axis=1)
y = df_encoded["SubscriptionRenewed"]

print("\nQ12. Features and Target Defined")

# Q13. Train-Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("\nQ13. Data Split Completed")

# Q14. Decision Tree Model

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

print("\nQ14. Decision Tree Trained")

# Q15. Decision Tree Accuracy

dt_predictions = dt_model.predict(X_test)

dt_accuracy = accuracy_score(y_test, dt_predictions)

print("\nQ15. Decision Tree Accuracy")
print(dt_accuracy)

# Q16. Confusion Matrix

cm = confusion_matrix(y_test, dt_predictions)

print("\nQ16. Confusion Matrix")
print(cm)

# Q17. KNN Classifier (K=5)

knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train, y_train)

print("\nQ17. KNN Trained")

# Q18. KNN Accuracy Comparison

knn_predictions = knn_model.predict(X_test)

knn_accuracy = accuracy_score(y_test, knn_predictions)

print("\nQ18. Accuracy Comparison")
print("Decision Tree:", dt_accuracy)
print("KNN:", knn_accuracy)

if knn_accuracy > dt_accuracy:
    print("KNN performed better.")
else:
    print("Decision Tree performed better.")

# Q19. Linear Regression

X_reg = df_encoded.drop("MonthlySpend", axis=1)
y_reg = df_encoded["MonthlySpend"]

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg,
    y_reg,
    test_size=0.20,
    random_state=42
)

lr_model = LinearRegression()

lr_model.fit(X_train_reg, y_train_reg)

print("\nQ19. Linear Regression Trained")

# Q20. Predict Monthly Spending

new_user = pd.DataFrame({
    "UserID": [9999],
    "Age": [30],
    "Gender": [1],
    "SubscriptionType": [1],
    "WatchHoursPerWeek": [15],
    "DevicesUsed": [2],
    "FavoriteGenre": [0],
    "AdClicks": [10],
    "SubscriptionRenewed": [1]
})

predicted_spend = lr_model.predict(new_user)

print("\nQ20. Predicted Monthly Spending")
print(predicted_spend[0])

"""Business Reflection Answers

1. Which factors appear to influence subscription renewal the most?

The most important factors affecting subscription renewal are Monthly Spend, Watch Hours Per Week, Subscription Type, and Age. Users who spend more and watch content regularly are generally more likely to renew their subscriptions.

2. Why is subscription renewal a classification problem?

Subscription renewal is a classification problem because the target variable has two categories: Yes or No. The model predicts which category a user belongs to.

3. Why is monthly spending a regression problem?

Monthly spending is a regression problem because it is a continuous numerical value. The model predicts an exact amount rather than a category.

4. Which algorithm performed better for renewal prediction?

The algorithm with the higher accuracy score performed better. Based on the model results, compare the accuracy of Decision Tree and KNN and choose the one with the higher value.

5. How could the platform use these predictions to improve customer retention?

Netflix can identify users who are likely to cancel their subscriptions and target them with personalized recommendations, special offers, or discounts. This can improve customer satisfaction and reduce subscription churn.
"""