# -*- coding: utf-8 -*-
"""Week3Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gVD0AXY_XgUXbRIhoPP2mbuy2Y1BmK5t
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df = pd.read_csv("agriculture_yield_dataset.csv")

print("Dataset Loaded Successfully")
df.head()

print("Rows and Columns:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nFirst 10 Records:")
print(df.head(10))

print("Data Types:\n")
print(df.dtypes)

print("\nMissing Values:\n")
print(df.isnull().sum())

stats = df.describe()

print(stats)

print("\nHighest Mean Feature:")
print(stats.loc["mean"].idxmax())

print("\nHighest Standard Deviation Feature:")
print(stats.loc["std"].idxmax())

columns = [
    "rainfall_mm",
    "temperature_c",
    "fertilizer_kg",
    "yield_ton_per_hectare"
]

for col in columns:
    plt.figure(figsize=(6,4))
    plt.hist(df[col], bins=20)
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Frequency")
    plt.show()

print(df["crop_type"].value_counts())

plt.figure(figsize=(6,4))
sns.countplot(data=df, x="crop_type")
plt.show()

print(df["soil_type"].value_counts())

plt.figure(figsize=(6,4))
sns.countplot(data=df, x="soil_type")
plt.show()

print("Most Common Soil Type:")
print(df["soil_type"].value_counts().idxmax())

plt.figure(figsize=(6,4))
plt.hist(df["yield_ton_per_hectare"], bins=20)
plt.title("Yield Distribution")
plt.xlabel("Yield")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(6,4))
plt.scatter(df["rainfall_mm"],
            df["yield_ton_per_hectare"])
plt.xlabel("Rainfall")
plt.ylabel("Yield")
plt.title("Rainfall vs Yield")
plt.show()

plt.figure(figsize=(6,4))
plt.scatter(df["fertilizer_kg"],
            df["yield_ton_per_hectare"])
plt.xlabel("Fertilizer")
plt.ylabel("Yield")
plt.title("Fertilizer vs Yield")
plt.show()

corr = df.corr(numeric_only=True)

print(corr)

plt.figure(figsize=(8,6))
sns.heatmap(corr,
            annot=True,
            cmap="coolwarm")
plt.show()

yield_corr = corr["yield_ton_per_hectare"].sort_values(ascending=False)

print(yield_corr)

print("Top 3 Features Correlated with Yield:")
print(yield_corr[1:4])

crop_avg = df.groupby("crop_type")["yield_ton_per_hectare"].mean()

print(crop_avg)

soil_avg = df.groupby("soil_type")["yield_ton_per_hectare"].mean()

print(soil_avg)

print("Highest Yield Crop:", crop_avg.idxmax())
print("Highest Yield Soil:", soil_avg.idxmax())

X = df.drop("yield_ton_per_hectare", axis=1)

X_encoded = pd.get_dummies(X)

print(X_encoded.head())

X = X_encoded

y = df["yield_ton_per_hectare"]

print("Target Variable:")
print(y.name)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("X_train Shape:", X_train.shape)
print("X_test Shape:", X_test.shape)
print("y_train Shape:", y_train.shape)
print("y_test Shape:", y_test.shape)

model = LinearRegression()

model.fit(X_train, y_train)

print("Intercept:")
print(model.intercept_)

coef_df = pd.DataFrame({
    "Feature": X_train.columns,
    "Coefficient": model.coef_
})

coef_df = coef_df.sort_values(
    by="Coefficient",
    ascending=False
)

print(coef_df)

print("Highest Positive Coefficient Feature:")
print(coef_df.iloc[0])