# -*- coding: utf-8 -*-
"""Week2Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M0l182pehEWfAu8tHQPBmypnzwig3XOI
"""

import pandas as pd
import numpy as np

from google.colab import files
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix

uploaded = files.upload()

df = pd.read_csv("hospital.csv")

print("Dataset Loaded Successfully")
print("\nFirst 5 Records:")
print(df.head())

# Q1: Loan Approval Prediction

dt_model = DecisionTreeClassifier()

print("\nQ1:")
print("Loan approval prediction is a Classification problem.")
print("Decision Tree is the most suitable algorithm because it handles classification efficiently.")

"""Q2.

Feature vs Label

Feature: Input variables used for prediction.
Label: Output variable that the model predicts.

Example: House Price Prediction

Features: Area, Number of Bedrooms, Location
Label: House Price

Q3.

How Decision Tree makes a prediction

A Decision Tree follows a series of questions (decision nodes).

Example:

Income > 50,000?
   |
   Yes
   |
Credit Score > 700?
   |
   Yes
   |
Purchase = Yes

The model moves through branches based on feature values until it reaches a final prediction.
"""

# Q4: KNN as Supervised Learning

knn = KNeighborsClassifier(n_neighbors=5)

print("\nQ4:")
print("KNN is a supervised learning algorithm because it uses labeled training data.")
print("Without labels, KNN cannot perform classification.")

# Q5: KNN Prediction

neighbors = ["Yes", "Yes", "No", "Yes", "No"]

prediction = max(set(neighbors), key=neighbors.count)

print("\nQ5:")
print("Nearest Neighbors:", neighbors)
print("Prediction:", prediction)
print("Reason: 'Yes' appears 3 times out of 5 neighbors.")

# Q6: Linear Regression Equation

x = 3
m = 2
b = 5

y = m * x + b

print("\nQ6:")
print("Equation: y = mx + b")
print("Where:")
print("x, Independent variable (input) =", x)
print("m, Slope of line =", m)
print("b, Intercept =", b)
print("y, Dependent variable (output) =", y)

# Q7: Correlation

data = {
    "X": [1, 2, 3, 4, 5],
    "Y": [2, 4, 6, 8, 10]
}

corr_df = pd.DataFrame(data)

print("\nQ7:")
print("Correlation Matrix:")
print(corr_df.corr())

print("\nInterpretation:")
print("+1 : Perfect Positive Correlation")
print(" 0 : No Correlation")
print("-1 : Perfect Negative Correlation")

"""Q8.

Disease Detection Result

Actual Condition	Prediction
Disease Present	Healthy
This is a False Negative (FN) prediction.
It is dangerous because a sick patient is classified as healthy and may not receive treatment.
"""

# Q9: Confusion Matrix

actual = [1, 0, 1, 1]
predicted = [1, 0, 0, 1]

cm = confusion_matrix(actual, predicted)

print("\nQ9:")
print("Confusion Matrix:")
print(cm)

print("\nPurpose:")
print("A Confusion Matrix evaluates the performance of a classification model.")
print("It shows True Positives, True Negatives, False Positives, and False Negatives.")

print("\nDifference from Correlation Matrix:")
print("Confusion Matrix -> Evaluates model predictions.")
print("Correlation Matrix -> Measures relationships between variables.")

"""Q10.

Algorithm Comparison

Decision Tree:

Makes predictions using a tree-like structure of decision rules.

KNN:

Classifies data based on the majority class of its nearest neighbors.

SVM:

Finds the optimal boundary (hyperplane) that separates classes.

Linear Regression:

Predicts continuous values using a straight-line relationship between variables.

Neural Network:

Learns complex patterns through interconnected layers of artificial neurons.
"""